# Generated by Django 5.1.4 on 2025-01-12 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Family', '0002_alter_familycode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=None)),
                ('plan_type', models.CharField(choices=[('MEAL', 'Meal'), ('VACATION', 'Vacation'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Family.family')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='PlanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Family.familymember', verbose_name='')),
            ],
            options={
                'verbose_name': 'PlanMember',
                'verbose_name_plural': 'PlanMembers',
            },
        ),
    ]
