# Generated by Django 5.1.4 on 2025-01-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
