# Generated by Django 5.1.4 on 2025-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0003_plan_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='date',
        ),
        migrations.AddField(
            model_name='plan',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
