# Generated by Django 5.1.4 on 2025-04-02 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Family', '0011_alter_familysettings_task_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('LIGHT', 'Light Bulb')], max_length=20)),
                ('is_on', models.BooleanField(default=False)),
                ('brightness', models.IntegerField(default=100)),
                ('room', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Family.family')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
