# Generated by Django 5.1.4 on 2025-02-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='family',
        ),
    ]
