# Generated by Django 5.1.4 on 2025-02-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationitem',
            name='operation',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='OperationItem',
        ),
    ]
