# Generated by Django 5.1.4 on 2025-04-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_remove_operationitem_operation_delete_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pocket',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='family',
        ),
        migrations.DeleteModel(
            name='Pocket',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
