# Generated by Django 5.1.4 on 2025-04-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance',
         '0005_remove_transaction_pocket_remove_transaction_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='income',
            field=models.BooleanField(default=False),
        ),
    ]
