# Generated by Django 5.1.4 on 2025-01-26 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Family', '0002_alter_familycode_user'),
        ('Inventory', '0001_initial'),
        ('Plan', '0002_alter_plan_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('finished', models.BooleanField()),
                ('list_type', models.CharField(choices=[('GROCERY', 'Grocery'), ('TASK', 'Task'), ('MEAL', 'Meal'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('datetime', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Family.family')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.plan')),
            ],
            options={
                'verbose_name': 'FamilyList',
                'verbose_name_plural': 'FamilyLists',
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.item')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='List.list')),
            ],
            options={
                'verbose_name': 'ListItem',
                'verbose_name_plural': 'ListItems',
            },
        ),
    ]
