# Generated by Django 5.1.4 on 2025-02-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0003_listitem_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
