# Generated by Django 5.1.4 on 2025-02-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0004_listitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='photo',
        ),
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name=''),
        ),
    ]
