# Generated by Django 5.1.4 on 2025-02-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
        ('List', '0005_remove_list_photo_list_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to='Finance.category',
                verbose_name=''),
        ),
        migrations.AddField(
            model_name='list',
            name='receipt_pdf',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True),
        ),
    ]
