# Generated by Django 5.1.4 on 2025-02-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_category_color'),
        ('List', '0007_alter_list_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to='Finance.category'),
        ),
    ]
