# Generated by Django 5.1.4 on 2025-04-02 00:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0009_alter_list_category_alter_list_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(
                choices=[
                    ('shopping',
                     'Shopping'),
                    ('tasks',
                     'Tasks')],
                default='tasks',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_lists',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='datetime',
            field=models.DateTimeField(
                default=django.utils.timezone.now),
        ),
    ]
