# Generated by Django 5.1.4 on 2025-04-02 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_remove_operationitem_operation_delete_operation_and_more'),
        ('List', '0010_alter_list_category_alter_list_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='Finance.category'),
        ),
        migrations.AlterField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='datetime',
            field=models.DateTimeField(
                auto_now_add=True),
        ),
    ]
