# Generated by Django 5.1.4 on 2025-04-02 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0011_alter_list_category_alter_list_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
