# Generated by Django 5.1.4 on 2025-03-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('invite',
                     'Family Invitation'),
                    ('request',
                     'Join Request'),
                    ('system',
                     'System Notification'),
                    ('general',
                     'General Notification'),
                    ('inventory_expiring',
                     'Item Expiring Soon'),
                    ('inventory_expired',
                     'Item Expired'),
                    ('inventory_low',
                     'Item Low Stock')],
                max_length=20),
        ),
    ]
