# Generated by Django 5.1.4 on 2025-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0004_notification_related_object_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_object_type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invite', 'Family Invitation'), ('request', 'Join Request'), ('system', 'System Notification'), ('general', 'General Notification')], max_length=20),
        ),
    ]
