# Generated by Django 5.1.4 on 2025-04-01 22:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0005_remove_notification_related_object_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycode',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='familycode',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
