# Generated by Django 5.1.4 on 2025-04-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0007_alter_familycode_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familycode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='familycode',
            name='expires_at',
        ),
    ]
