# Generated by Django 5.1.4 on 2025-04-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0009_alter_notification_notification_type_familysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familysettings',
            name='finance_notifications',
        ),
        migrations.AlterField(
            model_name='familysettings',
            name='task_notifications',
            field=models.CharField(
                choices=[
                    ('all',
                     'Visi šeimos nariai'),
                    ('parents',
                     'Tik tėvai'),
                    ('admin',
                     'Tik administratorius')],
                default='all',
                max_length=20,
                verbose_name='Turto pranešimai'),
        ),
    ]
