# Generated by Django 5.1.4 on 2025-04-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0011_alter_familysettings_task_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyRoom',
        ),
    ]
