# Generated by Django 5.1.4 on 2025-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0012_delete_familyroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='checkout_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
