# Generated by Django 5.1.4 on 2025-04-26 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0013_family_checkout_url_family_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
