# Generated by Django 5.1.4 on 2025-04-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0014_family_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
