# Generated by Django 5.1.4 on 2025-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='statistics_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='default_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemoperation',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemsubcategory',
            name='default_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
