# Generated by Django 5.1.4 on 2025-03-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_item_statistics_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('FOOD', 'Maistas'), ('MEDICINE', 'Vaistai')], default='FOOD', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.itemsubcategory'),
        ),
    ]
