# Generated by Django 5.1.4 on 2025-04-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_item_item_type_alter_item_avg_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='item',
            name='avg_price',
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
        migrations.DeleteModel(
            name='ItemSubCategory',
        ),
    ]
