# Generated by Django 5.1.4 on 2025-04-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_remove_itemsubcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('FOOD', 'Maistas'), ('MEDICINE', 'Vaistai'), ('CONTRACTS', 'Sutartys')], default='FOOD', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
