# Generated by Django 5.1.4 on 2025-05-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_item_item_type_alter_item_statistics_qty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemoperation',
            unique_together={('item', 'buy_date')},
        ),
    ]
