# Generated by Django 5.1.4 on 2025-05-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_alter_itemoperation_buy_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemoperation',
            unique_together={('item', 'exp_date')},
        ),
    ]
