name: Live Deployment Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  qa:
    uses: ./.github/workflows/qa.yml

  main-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Create config.json
        run: |
          echo '{
            "django": {
                "secret_key": "test-key",
                "debug": true,
                "allowed_hosts": ["localhost"]
            },
            "stripe": {
                "secret_key": "sk_test_51RICCBIxMSEn1DMFF97vaRvDnLm0RCa64qw9cZ0sYRsm92keiqBo4uRkMXnSzgN3mlQSXXyA50KwRy9wfoV0qObi00Ma0aIELE",
                "publishable_key": "pk_test_51RICCBIxMSEn1DMFxplEAXs0m0ioCbP0R1lBlclzSWjR8jXU6gMl6V6NxkVTMnffXAmeWqcki2hneW9kF6kO25Mg00onuBMWDh",
                "webhook_secret": "whsec_GLKuxqBvqWqwclzeZNxjIFRtT9fQW80t"
            },
            "site": {
                "url": "http://0.0.0.0:5000"
            }
          } ' > Nestify/config.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
         
      - name: Run migrations
        run: |
          python Nestify/manage.py makemigrations
          python Nestify/manage.py migrate
          
      - name: Check project
        run: |
          python Nestify/manage.py check
          
      - name: Run Django tests
        run: |
          python Nestify/manage.py test
          
      - name: Check for security issues
        run: |
          pip install bandit
          bandit -r . -x ./venv,./tests,./migrations