name: QA Workflow

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]
  workflow_call:

jobs:
  qa:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run linting
      run: |
        pip install flake8
        flake8 . --count --select=F --ignore=W293,E303,W291,W391,E302,E501,E305,W292,W504,F401 --show-source --statistics --max-complexity=10 --max-line-length=127
      continue-on-error: false 